from sklearn import hmm

models = {
'GMMHMM_5mix_5states_vitals_HR' : {
          'NSTATES' : 5,
          'MODEL' : hmm.GMMHMM(n_components=5, n_mix=5, covariance_type='full'),
          'NMIXTURES' : 5,
          'DT' : 0.5,
          'max_time' : None,
          'min_time' : None,
          'do_smoothing' : False,
          'do_imputation' : False,
          'vital_signs_to_use' : [ 'Heart Rate (beats/min)' ]
        },
'GMMHMM_3mix_3states_vitals_HR' : {
          'NSTATES' : 3,
          'MODEL' : hmm.GMMHMM(n_components=3, n_mix=3, covariance_type='full'),
          'NMIXTURES' : 3,
          'DT' : 0.5,
          'max_time' : None,
          'min_time' : None,
          'do_smoothing' : False,
          'do_imputation' : False,
          'vital_signs_to_use' : [ 'Heart Rate (beats/min)' ],
        },
'GMMHMM_5mix_5states_vitals_HR_tmin12hrs' : {
          'NSTATES' : 5,
          'MODEL' : hmm.GMMHMM(n_components=5, n_mix=5, covariance_type='full'),
          'NMIXTURES' : 5,
          'DT' : 0.5,
          'max_time' : None,
          'min_time' : 12.0,
          'do_smoothing' : False,
          'do_imputation' : False,
          'vital_signs_to_use' : [ 'Heart Rate (beats/min)' ],
        },
'GMMHMM_3mix_3states_vitals_HR_tmin12hrs' : {
          'NSTATES' : 3,
          'MODEL' : hmm.GMMHMM(n_components=3, n_mix=3, covariance_type='full'),
          'NMIXTURES' : 3,
          'DT' : 0.5,
          'max_time' : None,
          'min_time' : 12.0,
          'do_smoothing' : False,
          'do_imputation' : False,
          'vital_signs_to_use' : [ 'Heart Rate (beats/min)' ],
        },
'GMMHMM_5mix_5states_vitals_HR-BPS-BPD-RESP-TEMP_tmin12hrs_smooth30min' : {
          'NSTATES' : 5,
          'MODEL' : hmm.GMMHMM(n_components=5, n_mix=5, covariance_type='full'),
          'NMIXTURES' : 5,
          'DT' : 0.5,
          'max_time' : None,
          'min_time' : 12.0,
          'do_smoothing' : True,
          'do_imputation' : True,
          'vital_signs_to_use' : [ 
                                    'Heart Rate (beats/min)',
                                    'BP Noninvasive Diastolic (mm Hg)',
                                    'BP Noninvasive Systolic (mm Hg)',
                                    'Respirations (breaths/min)',
                                    'Temperature (degrees F)' ],
        },
'GMMHMM_5mix_5states_vitals_HR-BPS-BPD-RESP-TEMP_smooth30min' : {
          'NSTATES' : 5,
          'MODEL' : hmm.GMMHMM(n_components=5, n_mix=5, covariance_type='full'),
          'NMIXTURES' : 5,
          'DT' : 0.5,
          'max_time' : None,
          'min_time' : None,
          'do_smoothing' : True,
          'do_imputation' : True,
          'vital_signs_to_use' : [ 
                                    'Heart Rate (beats/min)',
                                    'BP Noninvasive Diastolic (mm Hg)',
                                    'BP Noninvasive Systolic (mm Hg)',
                                    'Respirations (breaths/min)',
                                    'Temperature (degrees F)' ],
        },
'GMMHMM_5mix_5states_vitals_HR-BPS-BPD-RESP-TEMP_smooth2hr' : {
          'NSTATES' : 5,
          'MODEL' : hmm.GMMHMM(n_components=5, n_mix=5, covariance_type='full'),
          'NMIXTURES' : 5,
          'DT' : 2.0,
          'max_time' : None,
          'min_time' : None,
          'do_smoothing' : True,
          'do_imputation' : True,
          'vital_signs_to_use' : [ 
                                    'Heart Rate (beats/min)',
                                    'BP Noninvasive Diastolic (mm Hg)',
                                    'BP Noninvasive Systolic (mm Hg)',
                                    'Respirations (breaths/min)',
                                    'Temperature (degrees F)' ],
        }
}